# Generated by Django 4.1.3 on 2022-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menu_items_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
