# Generated by Django 4.1.3 on 2022-11-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
