# Generated by Django 4.1.3 on 2022-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='ingredients_id',
            field=models.ManyToManyField(blank=True, to='menu.ingredient'),
        ),
    ]
