# Generated by Django 4.1.3 on 2022-11-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ingredient_menu_item_ingredients_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
