# Generated by Django 4.1.3 on 2022-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='ingredients_id',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
    ]
