# Generated by Django 4.1.3 on 2022-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_item_ingredients_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='ingredients_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='menu_id',
            field=models.ManyToManyField(to='menu.menu_item'),
        ),
    ]
