# Generated by Django 4.1.3 on 2022-11-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_item_ingredients_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
    ]
