# Generated by Django 4.1.3 on 2022-11-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_name_ingredient_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
    ]
