# Generated by Django 4.1.3 on 2022-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_title_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='ingredients_id',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='ingredients',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
    ]
