# Generated by Django 4.1.3 on 2022-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_category_id_menu_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
