# Generated by Django 4.1.3 on 2022-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_ingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='location',
            field=models.ManyToManyField(to='menu.location'),
        ),
    ]
