# Generated by Django 4.1.3 on 2022-11-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_location_menu_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
